import 'package:flutter_bloc/flutter_bloc.dart';
import '../../../data/models/profile.dart';
import '../../../data/repositories/student_repository.dart';
import 'student_event.dart';
import 'student_state.dart';

class StudentBloc extends Bloc<StudentEvent, StudentState> {
  final StudentRepository _repository;

  StudentBloc(this._repository) : super(const StudentState()) {
    on<LoadStudentsEvent>(_onLoadStudents);
    on<LoadStudentByIdEvent>(_onLoadStudentById);
    on<SearchStudentsEvent>(_onSearchStudents);
    on<CreateStudentEvent>(_onCreateStudent);
    on<UpdateStudentEvent>(_onUpdateStudent);
    on<DeleteStudentEvent>(_onDeleteStudent);
  }

  Future<void> _onLoadStudents(
    LoadStudentsEvent event,
    Emitter<StudentState> emit,
  ) async {
    emit(state.copyWith(status: StudentStatus.loading));

    try {
      final students = await _repository.getStudents();
      final classes = await _repository.getClasses();
      final faculties = await _repository.getFaculties();

      emit(
        state.copyWith(
          status: StudentStatus.loaded,
          students: students,
          filteredStudents: students,
          classes: classes,
          faculties: faculties,
        ),
      );
    } catch (e) {
      emit(
        state.copyWith(status: StudentStatus.error, errorMessage: e.toString()),
      );
    }
  }

  Future<void> _onLoadStudentById(
    LoadStudentByIdEvent event,
    Emitter<StudentState> emit,
  ) async {
    emit(state.copyWith(status: StudentStatus.loading));

    try {
      final student = await _repository.getStudentById(event.id);
      emit(
        state.copyWith(status: StudentStatus.loaded, selectedStudent: student),
      );
    } catch (e) {
      emit(
        state.copyWith(status: StudentStatus.error, errorMessage: e.toString()),
      );
    }
  }

  void _onSearchStudents(
    SearchStudentsEvent event,
    Emitter<StudentState> emit,
  ) {
    final query = event.query.toLowerCase();
    final filteredStudents = state.students.where((student) {
      return student.fullName.toLowerCase().contains(query) ||
          student.code.toLowerCase().contains(query);
    }).toList();

    emit(
      state.copyWith(filteredStudents: filteredStudents, searchQuery: query),
    );
  }

  Future<void> _onCreateStudent(
    CreateStudentEvent event,
    Emitter<StudentState> emit,
  ) async {
    emit(state.copyWith(status: StudentStatus.loading));

    try {
      final newStudent = Profile(
        id: '', // Will be generated by database
        code: event.code,
        fullName: event.fullName,
        classId: event.classId,
        isActive: true,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      await _repository.createStudent(newStudent);

      // Reload students list
      add(const LoadStudentsEvent());
    } catch (e) {
      emit(
        state.copyWith(status: StudentStatus.error, errorMessage: e.toString()),
      );
    }
  }

  Future<void> _onUpdateStudent(
    UpdateStudentEvent event,
    Emitter<StudentState> emit,
  ) async {
    emit(state.copyWith(status: StudentStatus.loading));

    try {
      final updatedStudent = Profile(
        id: event.id,
        code: event.code,
        fullName: event.fullName,
        classId: event.classId,
        isActive: event.isActive,
        createdAt: state.selectedStudent!.createdAt,
        updatedAt: DateTime.now(),
      );

      await _repository.updateStudent(updatedStudent);

      // Reload students list
      add(const LoadStudentsEvent());
    } catch (e) {
      emit(
        state.copyWith(status: StudentStatus.error, errorMessage: e.toString()),
      );
    }
  }

  Future<void> _onDeleteStudent(
    DeleteStudentEvent event,
    Emitter<StudentState> emit,
  ) async {
    emit(state.copyWith(status: StudentStatus.loading));

    try {
      await _repository.deleteStudent(event.id);

      // Reload students list
      add(const LoadStudentsEvent());
    } catch (e) {
      emit(
        state.copyWith(status: StudentStatus.error, errorMessage: e.toString()),
      );
    }
  }
}
